<?php if (AuthHelper::verify()) : ?>
    <div class="mt-5 w-25 mx-auto">
        <form method="POST" action="addClub">
            <div class="mb-3">
                <label ss="form-label">Club</label>
                <input type="text" class="form-control" name="Club">
            </div>
            <div class="mb-3">
                <label class="form-label">Liga</label>
                <input type="text" class="form-control" name="Liga">
            </div>
            <button type="submit" class="btn btn-primary">Agregar</button>
        </form>
    </div>
<?php endif ?>