<!DOCTYPE html>
<html lang="en">

<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styles.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Goleadores de fútbol</title>

</head>

<header>
    <h1 class="mt-5 w-25 mx-auto">Goleadores de fútbol</h1>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="mt-5 w-25 mx-auto container text-center">
        <div class="row align-items-center">
        <div class="col">
                <label class="btn btn-secondary"><a href="home">Home</a></label>
            </div>
            <div class="col">
                <label class="btn btn-secondary"><a href="clubes">Clubes</a></label>
            </div>
            
            
            <?php if (!AuthHelper::verify()) : ?>
                <a href="login">Login</a>
            <?php else : ?>
                <a href="logout">Logout (<?= $_SESSION['USER_EMAIL'] ?>)</a>
            <?php endif ?>
        </div>
    </div>
</nav>
</header>