<?php require './templates/header.phtml'; ?>
<?php require './templates/lista_goleadores_modificar.phtml'; ?>

<div class="mt-5 w-25 mx-auto">
    
    <table class="table">
    
        <thead>
            <tr>
                <th>#</th>
                <th>Goleador</th>
            </tr>
        </thead>
        <?php foreach ($goleadores as $goleador) : ?>
            <tbody>
                <tr>
                    <th><?= $goleador->Jugador_ID ?></th>
                    <td><?= $goleador->Nombre ?></td>
                     
                    <?php if (AuthHelper::verify()) : ?> 
                        <td><a href="delete/<?= $goleador->Jugador_ID ?> "><button class="btn btn-secondary ml-auto">Borrar</button></a></td>
                        <td><a href="preModify/<?= $goleador->Jugador_ID ?> "><button class="btn btn-secondary ml-auto">Modificar</button></a></td>
                    <?php endif ?>
                    
                    <td><a href="details/<?= $goleador->Jugador_ID ?> "><button class="btn btn-secondary ml-auto">Detalles</button></a>
                </tr>
            <?php endforeach ?>
            </tbody>
    </table>
</div>
<?php require './templates/footer.phtml'; ?>